apiVersion: v1
kind: Service
metadata:
  name: ship-manager-backend
spec:
  #type: LoadBalancer
  type: ExternalName
  externalName: ship-manager-backend.default.svc.cluster.local
  selector:
    app: ship-manager-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
