apiVersion: v1
kind: Service
metadata:
  name: contoso-ship-manager-frontend
spec:
  #type: LoadBalancer
  selector:
    app: contoso-ship-manager-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
