apiVersion: v1
kind: Service
metadata:
  name: ship-manager-backend
  #annotations:
  #      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  #type: LoadBalancer
  
  selector:
    app: ship-manager-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
